spring.application.name=homeApp
server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/home_app}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
mqtt.enabled=${MQTT_ENABLED:true}
mqtt.broker-url=${MQTT_BROKER_URL:tcp://localhost:1883}
mqtt.client-id=${MQTT_CLIENT_ID:homeapp-subscriber}
mqtt.topic=${MQTT_TOPIC:esp32/dht11}
